updatehub-sdk: doc: add a doc for the crate
UpdateHub/updatehub pull request #362
Opened 2020-10-19 16:05 UTC by Asakiz

Signed-off-by: asakiz <asakizin@gmail.com>

2020-10-19 20:29 UTC, Jonathas-Conceicao reviewed
Got some minor suggestions

2020-10-19 20:29 UTC, Jonathas-Conceicao commented on updatehub-sdk/src/listener.rs
> +/// The state(s) of the agent that can be handle.
```suggestion
/// The state of the agent that can be handled.
```

2020-10-19 20:29 UTC, Jonathas-Conceicao commented on updatehub-sdk/src/listener.rs
> +/// Struct that store the callback(s) for the state(s).
```suggestion
/// Struct that store the callbacks for the states.
```

2020-10-19 20:29 UTC, Jonathas-Conceicao commented on updatehub-sdk/src/listener.rs
> +/// UpdateHub to call the specified state callback(s).
```suggestion
/// Handler used to communicate with UpdateHub
/// to call commands on the state callbacks.
```

2020-10-19 20:29 UTC, Jonathas-Conceicao commented on updatehub-sdk/src/listener.rs
> +    /// ```text
This should be a `no_run` block with the irrelevant parts hidden so the compiler can still check them.

2020-10-19 20:29 UTC, Jonathas-Conceicao commented on updatehub-sdk/src/listener.rs
> +    /// 10-updatehub-sdk-statechange-trigger`.
```suggestion
    /// Start the agent to listen for messages on the socket at
    /// `/usr/share/updatehub/state-change-callbacks.d/
    /// 10-updatehub-sdk-statechange-trigger`.
```

2020-10-19 21:06 UTC, otavio commented on updatehub-sdk/src/listener.rs
> +    /// let mut listener = listener::StateChangeListener::default();
Does this compile?

2020-10-19 21:11 UTC, Asakiz commented on updatehub-sdk/src/listener.rs
> +    /// let mut listener = listener::StateChangeListener::default();
No, needs wrote the whole function.

2020-10-19 21:29 UTC, otavio approved these changes

2020-10-20 01:32 UTC, otavio requested changes

2020-10-20 02:05 UTC, Asakiz commented on updatehub-sdk/src/listener.rs
>  pub struct StateChangeListener {
I agree, but looking when we import the crate could be a little redundant.
e.g: `updatehub_sdk::listener::Listener::new()`.

2020-10-20 02:15 UTC, otavio commented on updatehub-sdk/src/listener.rs
>  pub struct StateChangeListener {
So just `StateChange`?

2020-10-20 12:54 UTC, Asakiz commented on updatehub-sdk/src/listener.rs
>  pub struct StateChangeListener {
It seems more appropriate.

2020-10-20 13:28 UTC, otavio submitted a review, later dismissed

2020-10-20 13:45 UTC, Jonathas-Conceicao requested changes
We are missing documentation for `Handler::cancel` e `Handler::proceed`.

2020-10-20 13:45 UTC, Jonathas-Conceicao commented on updatehub-sdk/src/listener.rs
> +    /// ```
This block does not produce the expected output, checkout the generated doc page.

2020-10-20 15:32 UTC, Jonathas-Conceicao approved these changes

2020-10-20 16:23 UTC, otavio approved these changes

2020-10-20 16:23 UTC, merged